In [2]:
'''import weight detection file 
    import vegetable detection file
    import vegetable classification filie
    '''
from vegetable_detection import detect_vegetable
from vegetable_classification import classify_vegetable
from  weights_detection import detect_weight
import numpy as np
import cv2
import matplotlib.pyplot as plt
import os

In [3]:
weight_stack = []
curr_weight = 0
curr_vegetable = "None"

In [4]:
def calculate_weight(weight):
    curr_weight =0
    weight = np.sum(weight)
    curr_weight = np.sum(weight)
    return curr_weight

In [5]:
weight = [[1,2,3],[4,5]]
print(calculate_weight(weight))

15


In [6]:
'''
    curr_weight represent jab update karna hai tab ka weight kitna hai
    curr_weight stack: store weights at all the positions
    curr_vegetable: kon si vegetable bech raha hai
    weight_in_frame: particular frame me kon kon se weights dikh rahe hai
'''

'\n    curr_weight represent jab update karna hai tab ka weight kitna hai\n    curr_weight stack: store weights at all the positions\n    curr_vegetable: kon si vegetable bech raha hai\n    weight_in_frame: particular frame me kon kon se weights dikh rahe hai\n'

In [7]:
def update_weight_stack(weight_stack, curr_detected_weight):
    '''
        updating weight person put in roi till now
    '''
    
    return 0

In [8]:
cap = cv2.VideoCapture(0)
while(True):
    ret, frame = cap.read()
    if(ret == False):
        continue
    '''
        detected region of interest from given frame
        then we crop roi from frame then classify vegetable
    '''
    vegetable_roi = np.array(detect_vegetable(frame)) # vegetable_roi in the form of (x1,y1, x2, y2)
    print(vegetable_roi)
    
    print(vegetable_roi.shape)
    cv2.imshow("frame" , frame)

    cropped_roi = frame[int(vegetable_roi[0]):int(vegetable_roi[3]), int(vegetable_roi[1]): int(vegetable_roi[3])]
    cv2.imshow("cropped",cropped_roi)
    vegetable_name = classify_vegetable(cropped_roi)
    '''
        if vegetable name  is none it means sabji bich gayi hai so we calculate weigtht for updating 
        weight he bought
    '''
    print(type(vegetable_name))
    if(vegetable_name == "None"):
        curr_weight = calculate_weight(weight_stack)
        weight_stack = []
    
    '''
        if vegetable name something it means we need to update weight continuously
    '''
    weight_in_frame = detect_weight(frame)
    if (cv2.waitKey(1) & 0xFF == 27):
        break 


[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
[  0.   0. 240. 320.]
(4,)
<class 'str'>
